# Configuration du serveur
server.port=8081

# Configuration MongoDB
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/gatcha_auth}

# Nom de l'application
spring.application.name=auth-service
