# Configuration du serveur
server.port=8085

# Configuration MongoDB
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/gatcha_combat}

# Nom de l'application
spring.application.name=combat-service

# URLs des autres services
AUTH_SERVICE_URL=${AUTH_SERVICE_URL:http://localhost:8081}
MONSTER_SERVICE_URL=${MONSTER_SERVICE_URL:http://localhost:8083}
