# Configuration du serveur
server.port=8082

# Configuration MongoDB
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/gatcha_player}

# Nom de l'application
spring.application.name=player-service

# URL de l'API d'authentification
AUTH_SERVICE_URL=${AUTH_SERVICE_URL:http://localhost:8081}
