# Configuration du serveur
server.port=8084

# Configuration MongoDB
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/gatcha_invocation}

# Nom de l'application
spring.application.name=invocation-service

# URLs des autres services
AUTH_SERVICE_URL=${AUTH_SERVICE_URL:http://localhost:8081}
MONSTER_SERVICE_URL=${MONSTER_SERVICE_URL:http://localhost:8083}
PLAYER_SERVICE_URL=${PLAYER_SERVICE_URL:http://localhost:8082}
